Add PyTorch example notebook
mlcommons/croissant pull request #444
Opened 2024-01-04 16:27 UTC by mkuchnik

Add an end-to-end example of how to Croissant in PyTorch using an adapter on top of mlcroissant and FLORES-200. The goal of the notebook is to provide a minimal yet somewhat realistic demo of how Croissant can be used in training. I am planning to expand on some of the features (e.g., performance) in future patches.

2024-01-05 15:48 UTC, mkuchnik commented
The 3 CI issues seem non-blocking to me, but let me know if you think otherwise:

* Python format error is outside this patch (log says `croissant/croissant/editor/events/resources.py`)
* The 2 Notebook tests are 10 minute timeouts likely due to ML training. The training time can be shortened to pass CI (and it would indeed be nice to tune the notebook to be faster), but I'd prefer to address that in a later patch. The notebook state already shows the full run, so run latency should not be a blocking factor.

2024-01-15 10:04 UTC, marcenacp requested changes
This is a great addition. Thanks for taking the time to implement this, Michael!

2024-01-15 10:04 UTC, marcenacp commented on python/mlcroissant/recipes/torch_adapter/dataloader.py
> +class LoaderFactory:
Do you need unit tests for this?

2024-01-16 01:09 UTC, mkuchnik commented
@marcenacp What are your thoughts on external dependencies? I attempted to make `torchdata` optional in incorporating the changes to `mlcroissant`, but I'm not sure how to handle this in the CI, which either does or does not need the dependencies. Currently, the PyType test is failing because of the dynamic import behavior of optional dependencies.

2024-01-16 01:10 UTC, mkuchnik commented on python/mlcroissant/recipes/PyTorch_FLORES200.ipynb
> +{
Should be updated now

2024-01-16 01:10 UTC, mkuchnik commented on python/mlcroissant/recipes/torch_adapter/dataloader.py
> +class LoaderFactory:
Added unit tests

2024-01-16 01:10 UTC, mkuchnik commented on python/mlcroissant/recipes/PyTorch_FLORES200.ipynb
> +    "import torch_adapter as ta\n",
Take a look at the current patch. I tried to make `mlcroissant.torch` have optional dependencies, but it makes the CI complicated.

2024-01-18 16:28 UTC, mkuchnik commented
@marcenacp Current patch passes CI and keeps framework dependencies as optional until used. Let me know if you have suggestions!

2024-01-19 08:01 UTC, marcenacp approved these changes
Thanks! Sorry for the delay in the review. Also left a few minor comments :)

2024-01-19 16:37 UTC, mkuchnik commented
@marcenacp I took my pass over the suggestions. Let me know if there are any outstanding issues.

2024-01-19 16:40 UTC, marcenacp approved these changes
Thanks!

2024-01-19 16:58 UTC, merged