Delete simple dataset as it is unused and it causes problems.
mlcommons/croissant pull request #503
Opened 2024-02-08 14:34 UTC by ccl-core

2024-02-08 14:34 UTC, ccl-core commented
Addresses #501

2024-02-08 15:18 UTC, marcenacp requested changes
Is there also a 0.8 version?

2024-02-08 16:15 UTC, ccl-core commented
There is, I deleted it too. Sorry, I thought we wanted to delete only the 1.0

2024-02-12 08:57 UTC, marcenacp approved these changes

2024-02-12 08:57 UTC, merged