Fix for issues in Specifications and README.md
mlcommons/croissant pull request #603
Opened 2024-03-14 14:32 UTC by dominik-kuhn

In this PR, a few issues in the spec files are addressed and fixed. Please review the changes and tell me, if this is the right way :)

Proposed changes:
- consistent and correct formatting in `croissant-spec.md`, `croissant-rai-spec.md` and `README.md`.
- fixed some compact IRI prefixes
- migrated all http links to https
- added some hyperlinks to expectedtypes

2024-03-15 09:56 UTC, dominik-kuhn commented on docs/croissant-spec.md
> +    <td><a href="https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#conformsTo">@dct:conformsTo</a></td>
Shouldnt that be 'dct:conformsTo' without an '@' instead of '@dct:conformsTo'?

2024-03-18 12:59 UTC, benjelloun requested changes
Hi Dominik,

Thank you for these great fixes!

My only reservation is around changing the namespace IRIs from http to https. Historically, schema.org has used http, and now supports both. It might make sense to switch to https for Croissant as well, but we should have a separate discussion and get consensus on that before making the change in the documentation.

For now, can you please keep these IRIs as is? (I realize they are not 100% consistent in the specs, which we should fix as well.)

Thank you,
Omar

2024-03-18 13:44 UTC, dominik-kuhn commented
Ok, I reverted the http to https IRI changes and removed the @ :) should I try to fix the IRI consistency in this PR?

2024-03-18 14:03 UTC, benjelloun approved these changes
Thanks!

2024-03-21 07:02 UTC, dominik-kuhn commented
feel free to merge this PR :) I see that there are a few other Prs coming, that are addressing the same issues, this PR addresses ;)

2024-03-21 09:49 UTC, merged